<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <Version>8.0.4</Version>
    <TargetFramework>net6.0</TargetFramework>
    <LangVersion>14.0</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <GeneratePackageOnBuild Condition="'$(Configuration)' == 'Release'">true</GeneratePackageOnBuild>
  </PropertyGroup>

  <PropertyGroup>
    <Authors>andhxl</Authors>
    <Description>A Blazor component that wraps SortableJS, a JavaScript library for reorderable drag-and-drop lists.</Description>
    <CopyrightYear>2025</CopyrightYear>
    <CurrentYear>$([System.DateTime]::Now.Year)</CurrentYear>
    <CopyrightYearRange Condition="'$(CopyrightYear)' == '$(CurrentYear)'">$(CopyrightYear)</CopyrightYearRange>
    <CopyrightYearRange Condition="'$(CopyrightYear)' != '$(CurrentYear)'">$(CopyrightYear)-$(CurrentYear)</CopyrightYearRange>
    <Copyright>© $(CopyrightYearRange) $(Authors)</Copyright>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://andhxl.github.io/blazor-sortable/</PackageProjectUrl>
    <PackageIcon>icon.png</PackageIcon>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageTags>blazor;sortablejs;sortable;reorder;drag;drag-and-drop</PackageTags>
    <RepositoryUrl>https://github.com/andhxl/blazor-sortable</RepositoryUrl>
  </PropertyGroup>

  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="6.0.0" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\icon.png" Pack="true" PackagePath="\" Visible="false" />
    <None Include="..\..\README.md" Pack="true" PackagePath="\" Visible="false" />
    <None Include="..\..\CHANGELOG.md" Pack="true" PackagePath="\" Visible="false" />
    <None Include="..\..\LICENSE.txt" Pack="true" PackagePath="\" Visible="false" />
    <None Include="..\..\THIRD-PARTY-NOTICES.txt" Pack="true" PackagePath="\" Visible="false" />
  </ItemGroup>

</Project>
